CREATE SCHEMA library;

CREATE TABLE library.ratings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id varchar(20) NOT NULL,
    user_id uuid NOT NULL REFERENCES auth.users(id),
    rating integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    UNIQUE(user_id, book_id) 
);

CREATE INDEX idx_ratings_book_id ON library.ratings(book_id);
CREATE INDEX idx_ratings_user_id ON library.ratings(user_id);

CREATE TABLE library.comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating_id bigint NOT NULL REFERENCES library.ratings(id),
    body text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    UNIQUE(rating_id)
);

CREATE INDEX idx_comments_rating_id ON library.comments(rating_id);
